package ca.oceansdata.dime.common.event;

public enum EventType {
    LOGIN,
    LOGOUT,
    DOCUMENT_UPLOAD,
    MANUAL_ATTRIBUTE_MATCH,
    MANUAL_ATTRIBUTE_MATCH_EDIT,
    DOWNLOAD_INTEGRATED_FILE,
    DOWNLOAD_ORIGINAL_FILE,
    COMMUNITY_TASK_MATCH,
    COMMUNITY_TASK_SKIP,
    COMMUNITY_TASK_FEEDBACK,
    COMMUNITY_MATCH_RESULT,
    PROFILE_FIELD_UPDATE,
    DOWNLOAD_DIME_TOOLS_FOR_WINDOWS,
    EDIT_SCHEMA_NAME,
    EDIT_SCHEMA_DESCRIPTION
}
